application: daqgit

version: 4-6-edit

runtime: python
api_version: 1

handlers:

- url: /quixe-work
  static_dir: quixe-work
  
- url: /Release
  static_dir: quixe-work/Hack_Hooks_Demo_Materials/Release

- url: /Browsies
  static_dir: quixe-work/Hack_Hooks_Demo_Materials/Browsies

- url: .*
  script: main.py

  


