application: daqgit
#fixing -
#testing -
#fixed unicode, basic server-errordisplay inline, 
#logposting-growth was actually a feature of errorhandling.
version: 4-3

runtime: python
api_version: 1

handlers:

- url: /quixe-work
  static_dir: quixe-work
  
- url: /Release
  static_dir: quixe-work/Hack_Hooks_Demo_Materials/Release

- url: /Browsies
  static_dir: quixe-work/Hack_Hooks_Demo_Materials/Browsies

- url: .*
  script: main.py

  


